version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rest-api-private-integration"
capabilities = "CAPABILITY_IAM"
template_file = "rest-api.yaml"
output_template_file = "rest-api-packaged-template.yaml"
region = "us-east-1"
resolve_s3 = true
s3_prefix = "rest-api-private-integration"
confirm_changeset = true
image_repositories = []

[default.package.parameters]
template_file = "rest-api.yaml"
stack_name = "rest-api-private-integration"

[default.validate.parameters]
template_file = "rest-api.yaml"
lint = true